version: "3.7"
services:
  db:
    image: mysql:8.0.20
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
#      MYSQL_USER: ${MYSQL_USER}
#      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3307:3306
    networks:
      - base
  base-php:
    build: php
    ports:
      - 80:80
    volumes:
      - ../my_project_name:/var/www/
    networks:
      - base
    depends_on:
      - db
    command: symfony serve --port=80
volumes:
  db:
networks:
  base: